<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DestinasiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Data wisata Jember (10 destinasi, field sesuai aplikasi)
        $destinasi = [
            [
                'nama' => 'Pantai Tanjung Papuma',
                'slug' => \Illuminate\Support\Str::slug('Pantai Tanjung Papuma'),
                'deskripsi' => 'Pantai indah dengan pasir putih dan pemandangan menakjubkan.',
                'deskripsi_lengkap' => 'Pantai Tanjung Papuma adalah salah satu destinasi wisata favorit di Jember dengan keindahan alam dan fasilitas lengkap.',
                'gambar' => '',
                'lokasi' => 'Jl. Raya Lojejer, Wuluhan, Jember',
                'harga_tiket' => 25000.00,
                'jam_buka' => '00:00:00',
                'jam_tutup' => '23:59:00',
                'rating' => 0,
                'jumlah_ulasan' => 0,
                'kategori' => 'Pantai',
                'kontak' => '0812-3456-7890',
                'maps_link' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Taman Botani Sukorambi',
                'slug' => \Illuminate\Support\Str::slug('Taman Botani Sukorambi'),
                'deskripsi' => 'Taman rekreasi keluarga dengan berbagai wahana edukasi dan alam.',
                'deskripsi_lengkap' => 'Taman Botani Sukorambi menawarkan pengalaman wisata edukasi dan alam yang menyenangkan untuk keluarga.',
                'gambar' => '',
                'lokasi' => 'Jl. Mujahir, Sukorambi, Jember',
                'harga_tiket' => 20000.00,
                'jam_buka' => '07:00:00',
                'jam_tutup' => '16:00:00',
                'rating' => 0,
                'jumlah_ulasan' => 0,
                'kategori' => 'Rekreasi',
                'kontak' => '(0331) 489xxxx',
                'maps_link' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Puncak Rembangan',
                'slug' => \Illuminate\Support\Str::slug('Puncak Rembangan'),
                'deskripsi' => 'Wisata pegunungan dengan udara sejuk dan pemandangan kota Jember dari ketinggian.',
                'deskripsi_lengkap' => 'Puncak Rembangan menawarkan panorama alam pegunungan dan fasilitas penginapan.',
                'gambar' => '',
                'lokasi' => 'Kemuning Lor, Arjasa, Jember',
                'harga_tiket' => 10000.00,
                'jam_buka' => '00:00:00',
                'jam_tutup' => '23:59:00',
                'rating' => 0,
                'jumlah_ulasan' => 0,
                'kategori' => 'Pegunungan',
                'kontak' => '(0331) 412xxxx',
                'maps_link' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Pantai Payangan (Teluk Love)',
                'slug' => \Illuminate\Support\Str::slug('Pantai Payangan Teluk Love'),
                'deskripsi' => 'Pantai unik dengan bukit berbentuk hati dan panorama laut selatan.',
                'deskripsi_lengkap' => 'Pantai Payangan terkenal dengan Teluk Love dan spot foto alam yang indah.',
                'gambar' => '',
                'lokasi' => 'Sumberejo, Ambulu, Jember',
                'harga_tiket' => 7500.00,
                'jam_buka' => '05:00:00',
                'jam_tutup' => '18:00:00',
                'rating' => 0,
                'jumlah_ulasan' => 0,
                'kategori' => 'Pantai',
                'kontak' => '-',
                'maps_link' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Kebun Teh Gunung Gambir',
                'slug' => \Illuminate\Support\Str::slug('Kebun Teh Gunung Gambir'),
                'deskripsi' => 'Agrowisata kebun teh dengan udara sejuk dan pemandangan hijau.',
                'deskripsi_lengkap' => 'Kebun Teh Gunung Gambir cocok untuk wisata alam dan edukasi pertanian.',
                'gambar' => '',
                'lokasi' => 'Gelang, Sumberbaru, Jember',
                'harga_tiket' => 10000.00,
                'jam_buka' => '06:00:00',
                'jam_tutup' => '17:00:00',
                'rating' => 0,
                'jumlah_ulasan' => 0,
                'kategori' => 'Agrowisata',
                'kontak' => '-',
                'maps_link' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Air Terjun Tancak',
                'slug' => \Illuminate\Support\Str::slug('Air Terjun Tancak'),
                'deskripsi' => 'Wisata alam air terjun dengan suasana asri dan segar.',
                'deskripsi_lengkap' => 'Air Terjun Tancak merupakan salah satu air terjun tertinggi di Jember.',
                'gambar' => '',
                'lokasi' => 'Suci, Panti, Jember',
                'harga_tiket' => 5000.00,
                'jam_buka' => '07:00:00',
                'jam_tutup' => '16:00:00',
                'rating' => 0,
                'jumlah_ulasan' => 0,
                'kategori' => 'Alam',
                'kontak' => '-',
                'maps_link' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Museum Tembakau',
                'slug' => \Illuminate\Support\Str::slug('Museum Tembakau'),
                'deskripsi' => 'Museum edukasi tentang sejarah dan industri tembakau di Jember.',
                'deskripsi_lengkap' => 'Museum Tembakau menampilkan koleksi dan informasi tentang tembakau.',
                'gambar' => '',
                'lokasi' => 'Jl. Kalimantan No. 1, Sumbersari, Jember',
                'harga_tiket' => 5000.00,
                'jam_buka' => '08:00:00',
                'jam_tutup' => '15:00:00',
                'rating' => 0,
                'jumlah_ulasan' => 0,
                'kategori' => 'Edukasi',
                'kontak' => '(0331) 330xxxx',
                'maps_link' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Pantai Watu Ulo',
                'slug' => \Illuminate\Support\Str::slug('Pantai Watu Ulo'),
                'deskripsi' => 'Pantai dengan batu memanjang seperti ular dan ombak besar.',
                'deskripsi_lengkap' => 'Pantai Watu Ulo terkenal dengan batu unik dan pemandangan laut selatan.',
                'gambar' => '',
                'lokasi' => 'Sumberejo, Ambulu, Jember',
                'harga_tiket' => 10000.00,
                'jam_buka' => '06:00:00',
                'jam_tutup' => '18:00:00',
                'rating' => 0,
                'jumlah_ulasan' => 0,
                'kategori' => 'Pantai',
                'kontak' => '-',
                'maps_link' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Dira Park Ambulu',
                'slug' => \Illuminate\Support\Str::slug('Dira Park Ambulu'),
                'deskripsi' => 'Taman rekreasi keluarga dengan wahana air dan hiburan.',
                'deskripsi_lengkap' => 'Dira Park Ambulu menawarkan berbagai wahana permainan dan kolam renang.',
                'gambar' => '',
                'lokasi' => 'Jl. Kota Blater, Ambulu, Jember',
                'harga_tiket' => 15000.00,
                'jam_buka' => '07:30:00',
                'jam_tutup' => '21:00:00',
                'rating' => 0,
                'jumlah_ulasan' => 0,
                'kategori' => 'Rekreasi',
                'kontak' => '0813-xxxx-xxxx',
                'maps_link' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Alun-Alun Jember',
                'slug' => \Illuminate\Support\Str::slug('Alun-Alun Jember'),
                'deskripsi' => 'Taman kota pusat keramaian dan aktivitas masyarakat Jember.',
                'deskripsi_lengkap' => 'Alun-Alun Jember menjadi tempat favorit untuk bersantai dan berkumpul.',
                'gambar' => '',
                'lokasi' => 'Jl. PB Sudirman, Patrang, Jember',
                'harga_tiket' => 0.00,
                'jam_buka' => '00:00:00',
                'jam_tutup' => '23:59:00',
                'rating' => 0,
                'jumlah_ulasan' => 0,
                'kategori' => 'Taman Kota',
                'kontak' => '-',
                'maps_link' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Hapus data lama agar tidak duplikat dan hindari error foreign key
        DB::table('pemesanan_tikets')->delete();
        DB::table('destinasis')->delete();
        DB::table('destinasis')->insert($destinasi);
    }
}