<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class FasilitasSeeder extends Seeder
{
    public function run()
    {
        $fasilitas = [
            [
                'nama' => 'Hotel Mutiara Jember',
                'kategori' => 'Hotel',
                'deskripsi' => 'Hotel bintang 4 dengan fasilitas lengkap di pusat kota Jember. Cocok untuk bisnis dan liburan keluarga.',
                'alamat' => 'Jl. Gatot Subroto No. 123, Jember',
                'telepon' => '0331-123456',
                'harga_permalam' => 450000,
                'kapasitas' => 100,
                'jarak_km' => 1.2,
                'rating' => '4.5',
                'fasilitas' => 'Kolam Renang, Restoran, Spa, WiFi Gratis, Parkir Luas',
                'foto' => 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=900&q=80',
                'website' => 'https://mutiarajember.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Jember Car Rental',
                'kategori' => 'Rental Mobil',
                'deskripsi' => 'Penyewaan mobil dengan harga terjangkau dan armada terawat. Siap melayani tour ke destinasi wisata.',
                'alamat' => 'Jl. Jawa No. 78, Jember',
                'telepon' => '0812-3456-7890',
                'harga_permalam' => 350000,
                'kapasitas' => 20,
                'jarak_km' => 2.5,
                'rating' => '4.3',
                'fasilitas' => 'AC, Asuransi, Driver Profesional, WiFi, Flexible Booking',
                'foto' => 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=900&q=80',
                'website' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Homestay Nusa Indah',
                'kategori' => 'Homestay',
                'deskripsi' => 'Homestay dengan suasana keluarga, lokasi strategis dekat destinasi wisata. Nyaman dan terjangkau.',
                'alamat' => 'Jl. Diponegoro No. 89, Jember',
                'telepon' => '0813-9876-5432',
                'harga_permalam' => 150000,
                'kapasitas' => 10,
                'jarak_km' => 3.1,
                'rating' => '4.6',
                'fasilitas' => 'WiFi, Dapur Bersama, Area Terbuka, Parkir, Nyaman',
                'foto' => 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=900&q=80',
                'website' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Wisma Sari Indah',
                'kategori' => 'Wisma',
                'deskripsi' => 'Wisma murah dan nyaman, cocok untuk backpacker dan keluarga.',
                'alamat' => 'Jl. Kalimantan No. 45, Jember',
                'telepon' => '0331-654321',
                'harga_permalam' => 100000,
                'kapasitas' => 30,
                'jarak_km' => 2.0,
                'rating' => '4.0',
                'fasilitas' => 'WiFi, Parkir, Sarapan, AC',
                'foto' => 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=900&q=80',
                'website' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Kost Putri Mawar',
                'kategori' => 'Kost',
                'deskripsi' => 'Kost putri bulanan, aman dan nyaman, dekat kampus.',
                'alamat' => 'Jl. Mawar No. 12, Jember',
                'telepon' => '0812-2222-3333',
                'harga_permalam' => 50000,
                'kapasitas' => 15,
                'jarak_km' => 1.8,
                'rating' => '4.2',
                'fasilitas' => 'WiFi, Dapur, Laundry, Parkir Motor',
                'foto' => 'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=900&q=80',
                'website' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Hotel Cempaka',
                'kategori' => 'Hotel',
                'deskripsi' => 'Hotel budget dengan fasilitas standar dan lokasi strategis.',
                'alamat' => 'Jl. Cempaka No. 7, Jember',
                'telepon' => '0331-777888',
                'harga_permalam' => 200000,
                'kapasitas' => 40,
                'jarak_km' => 2.7,
                'rating' => '4.1',
                'fasilitas' => 'AC, TV, Parkir, Sarapan',
                'foto' => 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=900&q=80',
                'website' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Rental Motor Jember',
                'kategori' => 'Rental Motor',
                'deskripsi' => 'Sewa motor harian/mingguan, armada baru dan terawat.',
                'alamat' => 'Jl. Sumatra No. 21, Jember',
                'telepon' => '0812-3333-4444',
                'harga_permalam' => 75000,
                'kapasitas' => 25,
                'jarak_km' => 2.9,
                'rating' => '4.4',
                'fasilitas' => 'Helm, Jas Hujan, Asuransi, Parkir',
                'foto' => 'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=900&q=80',
                'website' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Hotel Bintang Mulia',
                'kategori' => 'Hotel',
                'deskripsi' => 'Hotel modern dengan ballroom dan fasilitas meeting.',
                'alamat' => 'Jl. Brawijaya No. 88, Jember',
                'telepon' => '0331-888999',
                'harga_permalam' => 600000,
                'kapasitas' => 120,
                'jarak_km' => 1.5,
                'rating' => '4.7',
                'fasilitas' => 'Ballroom, Meeting Room, WiFi, Restoran',
                'foto' => 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=900&q=80',
                'website' => 'https://bintangmuliahotel.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Penginapan Sederhana',
                'kategori' => 'Penginapan',
                'deskripsi' => 'Penginapan murah, cocok untuk backpacker.',
                'alamat' => 'Jl. Melati No. 5, Jember',
                'telepon' => '0812-5555-6666',
                'harga_permalam' => 80000,
                'kapasitas' => 8,
                'jarak_km' => 3.5,
                'rating' => '4.0',
                'fasilitas' => 'Fan, Parkir, Dapur',
                'foto' => 'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=900&q=80',
                'website' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Wisma Keluarga Bahagia',
                'kategori' => 'Wisma',
                'deskripsi' => 'Wisma keluarga dengan fasilitas lengkap dan harga terjangkau.',
                'alamat' => 'Jl. Kenanga No. 10, Jember',
                'telepon' => '0331-999000',
                'harga_permalam' => 120000,
                'kapasitas' => 20,
                'jarak_km' => 2.2,
                'rating' => '4.3',
                'fasilitas' => 'WiFi, AC, Parkir, Sarapan',
                'foto' => 'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=900&q=80',
                'website' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];
        DB::table('fasilitas')->delete();
        DB::table('fasilitas')->insert($fasilitas);
    }
}
